![UCA](http://caillau.perso.math.cnrs.fr/logo-uca.png)
## L2 MIASHS - ANDE
# Projet

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jbcaillau/ande/master?urlpath=lab/tree/proj/proj.ipynb)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jbcaillau/ande/blob/master/proj/proj.ipynb)

## Exercice 1
On se place sur $X = {\mathbf{R}}^3_+$ et on considère la relation de préférence notée $\preccurlyeq$ définie comme suit : 
$(x_1,x_2,x_3) \preccurlyeq (y_1,y_2,y_3)$ si et seulement pour au moins deux valeurs de $i$ dans $\{1, 2, 3\}$ on a $x_i \leq y_i$.

### 1.1
Montrer cette relation de préférence est complète.

### 1.2
À l'aide d'un contrexemple, montrer que cette relation de préférence n'est pas transitive.

**1.1 Une relation de préférence $\preccurlyeq$ est dite complète si tous les éléments de X sont comparables : 
($\forall (x,y) \in X^2 : X*X$) : $x\preccurlyeq y$ ou $y\preccurlyeq x$.** 

**Ainsi soit $(x_1,x_2,x_3)$ et $(y_1,y_2,y_3) \in R^3_+$ : Montrons que $(x_1,x_2,x_3)\preccurlyeq (y_1,y_2,y_3)$ ou $(y_1,y_2,y_3)\preccurlyeq (x_1,x_2,x_3)$ :** 

**- Si $x_1\le y_1$ et $x_2\le y_2$ et $x_3\le y_3$, alors $(x_1,x_2,x_3)\preccurlyeq(y_1,y_2,y_3)$**

**- Si $x_1 \le y_1$ et $x_2\le y_2$ et $x_3\ge y_3$, alors $(x_1,x_2,x_3)\preccurlyeq(y_1,y_2,y_3)$**

**- Si $x_1\le y_1$ et  $x_2\ge y_2$ et  $x_3\ge y_3$, alors $(y_1,y_2,y_3)\preccurlyeq (x_1,x_2,x_3)$**

**- Si $x_1\ge y_1$ et  $x_2\ge y_2$ et  $x_3\ge y_3$, alors $(y_1,y_2,y_3)\preccurlyeq (x_1,x_2,x_3)$**

**Ainsi, on a examiné tous les cas possibles et conclut à une comparaison dans tous les cas donc la relation de préférence est complète.**



**1.2 Une relation de préférence est dite transitive si : ($\forall(x,y,z)\in X^3)$ : $x\preccurlyeq y$ et $y\preccurlyeq z \Rightarrow x\preccurlyeq z$.**

**Montrons à l'aide d'un contre-exemple que cette relation n'est pas transitive : Supposons $(x_1,x_2,x_3), (y_1,y_2,y_3), (z_1,z_2,z_3)$ \in $R^3_+$, par transitivité si $x_i\le y_i\le z_i$ cela implique $x_i\le z_i$.**

**Prenons par exemple $x= (1,1,1), y=(0,1,1), z=(1,0,1)$ : dans ce cas on a $x\preccurlyeq y$ et $y\preccurlyeq z$ mais on a pas $x\preccurlyeq z$ donc cette relation de préférence n'est pas transitive.**


## Exercice 2B
### 2.1
Discuter du maximum de la fonction d'utilité $U(x,y)=2x^3 + x^2 y - 9x^2 - 2xy + 2x - 4y + 20$ sous les contraintes $x\geq 0$, $y\geq 0$ et la contrainte de revenu $5x+3y\leq r$ pour $r=5$ puis pour $r=20$.
Vérifier avec un dessin du graphe de $U$.

### 2.2
Soit $U:(x,y)\mapsto U(x,y)$ une fonction d'utilité (à valeurs dans $\mathbf{R}$) dont on cherche le maximum sous les contraintes conjointes $c_1(x,y)\leq 0$, $c_2(x,y)\leq 0$ et $c_3(x,y)\leq 0$. On ne précise ni $U$ ni les $c_i$.
On a exécuté avec Sagemath la suite d'instructions ci-dessous et obtenu la réponse qui suit. Que peut on dire des couples $(x,y)$ où $U$ est maximal ? Expliquer.
Que peut on dire des couples $(x,y)$ où $U$ est minimal ?

```python
var('l,m,n')
L = (U-l*c1-m*c2-n*c3).gradient()(x,y)
S = solve([L[0]==0,L[1]==0,l*c1==0,m*c2==0,n*c3==0],[x,y,l,m,n])

print '(x,y), (l,m,n), (c1(x,y),c2(x,y),c3(x,y)) ='
ns = 1
for s in S:
    x,y,l,m,n = (s[i].rhs().n(digits=2) for i in range(5))
    print ns,(x,y),(l,m,n),(c1(x,y),c2(x,y),c3(x,y))
    ns = ns+1

(x,y), (l,m,n), (c1(x,y),c2(x,y),c3(x,y)) =
1 (1.0, -2.0) (0.00, 0.00, 0.00) (-1.0, 2.0, -11.)  
2 (0.00, -1.0) (-2.0, 0.00, 0.00) (0.00, 1.0, -10.)  
3 (0.00, 0.00) (-4.0, -2.0, 0.00) (0.00, 0.00, -5.0)  
4 (1.5, -0.17) (0.00, 0.00, 0.92) (-1.5, 0.17, 0.00)  
5 (0.00, 1.0) (-2.8, 0.00, 0.80) (0.00, -1.0, 0.00)  
6 (1.2, 0.00) (0.00, 0.50, 1.0) (-1.2, 0.00, 0.00)  
```


**2.1 Maximiser l'utilité revient à "faire le meilleur choix possible" étant donné notre budget. On va donc devoir résoudre un problème  d'optimisation afin de trouver $\bar{x}=(\bar{x},\bar{y})\in\mathbf{R^2} $ tel qu'on maximise l'utilité $U(x,y)$ sous la contrainte $P1.x + P2.y \le r $**.

**Montrons dans un premier temps que les préférences associés à la fonction d'utilité  $U(x,y)=2x^3 + x^2 y - 9x^2 - 2xy + 2x - 4y + 20$ sont convexes :**

**Soit $U_0 \gt 0$ un niveau d'utilité fixé. 
$$U(x,y) = U_0$$**
$$\Rightarrow 2x^3 + x^2 y - 9x^2 - 2xy + 2x - 4y + 20 = U_0$$

**Tirons y en fonction de x :**
$$ f(x) = y = {2x^3-9x^2+2x+20-U_0\over-x^2+2x + 4}$$
**Comme $x\ge 0, f(x)$ est dérivable.**

**On en déduit $f'(x) \lt 0$ et $f''(x)\gt 0$. Donc les préférences sont convexes.**

**Par définition, le lagrangien du problème est : $$ \mathcal{L}=U(x,y) - \lambda*(5x+3y-5)$$
$$ \mathcal{L}=2x^3 + x^2 y - 9x^2 - 2xy + 2x - 4y + 20-\lambda*(5x+3y-5)$$**



## Exercice 3A
On considère le jeu de poker simplifié à deux joueurs suivant. Trois mains sont possibles, numérotées de $1$ à $3$, de la plus faible à la plus forte. Chaque joueuse, ayant reçu l'une de ces mains, met un jeton au pot. Le jeu se déroule ensuite selon le schéma ci-dessous (jeu séquentiel), sachant que, pour _miser_ ou pour _voir_, une joueuse doit rajouter un jeton au pot (rien à mettre au pot si la joueuse choisit de _passer_). La gagnante remporte le pot. 
La joueuse 2 triche et, à l'insu de la joueuse 1, s'est arrangée avec le croupier qui distribue les cartes afin que la main $(2, 3)$ (qui lui est favorable) sorte plus souvent que les autres, avec une probabilité de $1/4$ (les cinq autres mains sortant avec une même probabilité de $3/20$).

![Règles du jeu](https://github.com/jbcaillau/ande/blob/master/proj/poker.png?raw=1)

### 3.1
Calculer la matrice des gains (en espérance) du jeu sous forme normale.

### 3.2
Déterminer les stratégies _prudentes_ de chaque joueuse, c'est à dire la stratégie $\max_i \min_j$ pour la joueuse 1 et $\min_j \max_i$ de la joueuse 2. Y a-t-il équilibre (en stratégies pures) ?

### 3.3
Déterminer les éventuelles stratégies dominées de chaque joueuse.

### 3.4
Déterminer la valeur du jeu en stratégies mixtes, et donner un couple de stratégies mixtes en équilibre.

### 3.5
Un nouveau croupier remplace le précédent. Quatre mains sont désormais possibles, numérotées de $1$ à $4$, de la plus faible à la plus forte. Donner l'ensemble des stratégies (pures) pour chaque joueuse dans le jeu sous forme normale.

### 3.6 (BONUS)
Reprendre les questions 3.1 à 3.5 en supposant le nouveau croupier honnête, de sorte que toutes les combinaisons de mains sont équiprobables.

**3.1 Calculons la matrice des gains du jeu sous forme normale :**

In [0]:
from math import * 
import numpy as np

from scipy.optimize import linprog

# Exceptions
class StrategieInconnue(Exception):
    """Strategie Inconnue
    
    Attribut :
        s -- stratégie
    """
    def __init__(self, s):
        self.s = s

class MainInconnue(Exception):
    """Main Inconnue
    
    Attribut :
        m -- main
    """
    def __init__(self, m):
        self.m = m

class MainVide(Exception):
    """Main Vide
    """

class PbResolution(Exception):
    """Probleme de resolution du LP
    """

# Stratégies de la joueuse 1
S1m = [ 'M', 'PV', 'PP' ] # M = Mise, P = Passe, V = Voit
l1 = len(S1m)
S1 = [ (S1m[i], S1m[j], S1m[k]) for i in range(0, l1) for j in range(0, l1) for k in range(0, l1) ]
m = len(S1)

# Stratégies de la joueuse 2
S2m = [ 'VP', 'VM', 'PP', 'PM' ] # M = Mise, P = Passe, V = Voit
l2 = len(S2m)
S2 = [ (S2m[i], S2m[j], S2m[k]) for i in range(0, l2) for j in range(0, l2) for k in range(0, l2) ]
n = len(S2)

# Mains pouvant être distribuées
Mains = [ (1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2) ] # main 1 < main 2 < main 3

# Calcul des gains
def gmfun(s1, s2, main):
    """g = gmfun(s1, s2, main)
    Gain de la joueuse 1 en fonction de la main distribuée aux deux joueuses.

    s1 : triplet de stratégies de la joueuse 1
    s2 : triplet de stratégies de la joueuse 2
    main : main (= cartes) distribuées aux joueuses
    """
    if s1 not in S1: raise StrategieInconnue(s1)
    if s2 not in S2: raise StrategieInconnue(s2)
    if main not in Mains: raise MainInconnue(main)

    s1m = s1[main[0]-1]
    s2m = s2[main[1]-1]

    if s1m[0] is 'M': # la joueuse 1 mise

        if s2m[0] is 'V': # la joueuse 2 voit
            if main[0] > main[1]: gm = 2 # la meilleure main emporte le pot
            else: gm = -2
        elif s2m[0] is 'P': # la joueuse 2 passe
            gm = 1 # la joueuse 1 emporte le pot
        else: raise StrategieInconnue(s2)

    elif s1m[0] is 'P': # la joueuse 1 passe

        if s2m[1] is 'P': # la joueuse 2 passe
            if main[0] > main[1]: gm = 1 # la meilleure main emporte le pot
            else: gm = -1
        elif s2m[1] is 'M': # la joueuse 2 mise
            if s1m[1] is 'V': # la joueuse 1 voit
                if main[0] > main[1]: gm = 2 # la meilleure main emporte le pot
                else: gm = -2
            elif s1m[1] is 'P': # la joueuse 1 passe
                gm = -1
            else: raise StrategieInconnue(s1)
        else: raise StrategieInconnue(s2)

    else: raise StrategieInconnue(s1)

    return gm

def gfun(s1, s2):
    """g = gfun(s1, s2)
    Gain en espérance de la joueuse 1 
 
    s1 : triplet de stratégies de la joueuse 1
    s2 : triplet de stratégies de la joueuse 2
    """
    l = len(Mains)
    if l is 0: raise MainVide
    g = 0.
    for i in range(0, l):
      if i==3 :
        g = g + (1/4) * gmfun(s1, s2, Mains[i])
      else:
        g = g + (3/20) * gmfun(s1, s2, Mains[i])
    return g

A = np.zeros((m, n))
for i in range(0, m):
    for j in range(0, n):
        A[i, j] = gfun(S1[i], S2[j])

print(A)

[[-0.2 -0.2  1.  ... -0.2  1.   1. ]
 [-0.5 -0.5  0.7 ...  0.1  1.3  1.3]
 [-0.5 -0.5  0.7 ... -0.8  0.4  0.4]
 ...
 [ 0.2  0.2  0.2 ... -0.4 -0.4 -0.4]
 [-0.1 -0.1 -0.1 ... -0.1 -0.1 -0.1]
 [-0.1 -0.1 -0.1 ... -1.  -1.  -1. ]]


**3.2 Déterminons les stratégies prudentes de chaque joueuse :
 Ici, la joueuse 1 cherche à maximiser son pire gain, on cherche donc la valeur $$\alpha =\max_{i=1,m} \min_{j=1,n} a_{ij}.$$
Une stratégie prudente pour la joueuse 1 est donc $\bar{i}$ tel que
$$\min_{j=1,n} a_{\bar{i}j} = \max_{i=1,m} \min_{j=1,n} a_{ij}. $$
Symétriquement, la joueuse 2 cherche à minimiser sa pire perte, donc cherche la valeur
$$ \beta := \min_{j=1,n} \max_{i=1,m} a_{ij}. $$ 
Une stratégie prudente pour la joueuse 2 est donc $\bar{j}$ tel que
$$ \max_{i=1,m} a_{i\bar{j}} = \max_{i=1,m} \min_{j=1,n} a_{ij}. $$**


**3.3 Déterminons les stratégies dominées de chaque joueuse : Une stratégie dominée pour une joueuse 1 est une stratégie qui lui donne toujours un gain inférieur à celui d’au moins une des autres stratégies à sa disposition (quel que soit la stratégie de la joueuse 2)**

**3.4 Déterminons la valeur du jeu en stratégies mixtes :**

**Les stratégies mixtes consistent à jouer un grand nombre de jeu et à fixer les probabilités pour jouer telle ou telle stratégie. On sait qu’il existe toujours au moins une paire de stratégies mixtes qui forme un équilibre de Nash.**

In [0]:
# Calcul de la valeur du jeu en stratégies mixtes (minimax)
c =-np.ones(n) # min (c|x) = -max (-c|x)
b = np.ones(m) # Ax <= b 
bounds = (0, None) # 0 <= x

method='simplex'
#method='revised simplex'
#method='interior-point'

res = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method=method)
if not res.success: raise PbResolution

v = 1 / (-res.fun)
x = v * res.x
v = v - d
xx = np.round_(x, decimals=8)

print('v = ', v)
print('x = ', xx)
print('')
print("Stratégie mixte optimale de la joueuse 2 :")
for j in range(0, n):
    if xx[j] > 0:
        print(S2[j], "avec proba", xx[j])

In [0]:
import numpy as np
from scipy.optimize import linprog

# Exceptions
class StrategieInconnue(Exception):
    """Strategie Inconnue
    
    Attribut :
        s -- stratégie
    """
    def __init__(self, s):
        self.s = s

class MainInconnue(Exception):
    """Main Inconnue
    
    Attribut :
        m -- main
    """
    def __init__(self, m):
        self.m = m

class MainVide(Exception):
    """Main Vide
    """

class PbResolution(Exception):
    """Probleme de resolution du LP
    """

# Stratégies de la joueuse 1
S1m = [ 'M', 'PV', 'PP' ] # M = Mise, P = Passe, V = Voit
l1 = len(S1m)
S1 = [ (S1m[i], S1m[j], S1m[k]) for i in range(0, l1) for j in range(0, l1) for k in range(0, l1) ]
m = len(S1)

# Stratégies de la joueuse 2
S2m = [ 'VP', 'VM', 'PP', 'PM' ] # M = Mise, P = Passe, V = Voit
l2 = len(S2m)
S2 = [ (S2m[i], S2m[j], S2m[k]) for i in range(0, l2) for j in range(0, l2) for k in range(0, l2) ]
n = len(S2)

# Mains pouvant être distribuées
Mains = [ (1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2) ] # main 1 < main 2 < main 3

# Calcul des gains
def gmfun(s1, s2, main):
    """g = gmfun(s1, s2, main)
    Gain de la joueuse 1 en fonction de la main distribuée aux deux joueuses.

    s1 : triplet de stratégies de la joueuse 1
    s2 : triplet de stratégies de la joueuse 2
    main : main (= cartes) distribuées aux joueuses
    """
    if s1 not in S1: raise StrategieInconnue(s1)
    if s2 not in S2: raise StrategieInconnue(s2)
    if main not in Mains: raise MainInconnue(main)

    s1m = s1[main[0]-1]
    s2m = s2[main[1]-1]

    if s1m[0] is 'M': # la joueuse 1 mise

        if s2m[0] is 'V': # la joueuse 2 voit
            if main[0] > main[1]: gm = 2 # la meilleure main emporte le pot
            else: gm = -2
        elif s2m[0] is 'P': # la joueuse 2 passe
            gm = 1 # la joueuse 1 emporte le pot
        else: raise StrategieInconnue(s2)

    elif s1m[0] is 'P': # la joueuse 1 passe

        if s2m[1] is 'P': # la joueuse 2 passe
            if main[0] > main[1]: gm = 1 # la meilleure main emporte le pot
            else: gm = -1
        elif s2m[1] is 'M': # la joueuse 2 mise
            if s1m[1] is 'V': # la joueuse 1 voit
                if main[0] > main[1]: gm = 2 # la meilleure main emporte le pot
                else: gm = -2
            elif s1m[1] is 'P': # la joueuse 1 passe
                gm = -1
            else: raise StrategieInconnue(s1)
        else: raise StrategieInconnue(s2)

    else: raise StrategieInconnue(s1)

    return gm

def gfun(s1, s2):
    """g = gfun(s1, s2)
    Gain en espérance de la joueuse 1 (toutes les mains sont supposées équiprobables)
 
    s1 : triplet de stratégies de la joueuse 1
    s2 : triplet de stratégies de la joueuse 2
    """
    l = len(Mains)
    if l is 0: raise MainVide
    g = 0.
    for i in range(0, l):
        g = g + (1/l) * gmfun(s1, s2, Mains[i])
    return g

A = np.zeros((m, n))
for i in range(0, m):
    for j in range(0, n):
        A[i, j] = gfun(S1[i], S2[j])

d = abs(np.min(A)) + 1
A = A + d # translate les gains pour garantir une valeur > 0 du jeu mixte

# Calcul de la valeur du jeu en stratégies mixtes (minimax)
c =-np.ones(n) # min (c|x) = -max (-c|x)
b = np.ones(m) # Ax <= b 
bounds = (0, None) # 0 <= x

method='simplex'
#method='revised simplex'
#method='interior-point'

res = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method=method)
if not res.success: raise PbResolution

v = 1 / (-res.fun)
x = v * res.x
v = v - d
xx = np.round_(x, decimals=8)

print('v = ', v)
print('x = ', xx)
print('')
print("Stratégie mixte optimale de la joueuse 2 :")
for j in range(0, n):
    if xx[j] > 0:
        print(S2[j], "avec proba", xx[j])