![UCA](http://caillau.perso.math.cnrs.fr/logo-uca.png)
## L2 MIASHS - ANDE
# Projet

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jbcaillau/ande/master?urlpath=lab/tree/proj/proj.ipynb)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jbcaillau/ande/blob/master/proj/proj.ipynb)

## Exercice 1
On se place sur $X = {\mathbf{R}}^3_+$ et on considère la relation de préférence notée $\preccurlyeq$ définie comme suit : 
$(x_1,x_2,x_3) \preccurlyeq (y_1,y_2,y_3)$ si et seulement pour au moins deux valeurs de $i$ dans $\{1, 2, 3\}$ on a $x_i \leq y_i$.

### 1.1
Montrer cette relation de préférence est complète.

### 1.2
À l'aide d'un contrexemple, montrer que cette relation de préférence n'est pas transitive.

REPONSES:

1.1

Une relation de préférence notée $\preccurlyeq$ est dite complète si tous les éléments de $X$ sont comparables (Quelques soient ($x$,$y$) dans $X^2$, $x \leq y$ ou $y \leq x$.). 

Est-elle complète dans notre cas?

Soient ($x_1$, $x_2$, $x_3$) et ($y_1$, $y_2$, $y_3$) $\in$ $X$. Il faut montrer que ($x_1$, $x_2$, $x_3$) $\preccurlyeq$ ($y_1$, $y_2$, $y_3$) ou ($y_1$, $y_2$, $y_3$) $\preccurlyeq$ ($x_1$, $x_2$, $x_3$)

si $x_1 \leq y_1$ et $x_2 \leq y_2$,  alors ($x_1$, $x_2$, $x_3$) $\preccurlyeq$ ($y_1$, $y_2$, $y_3$)

si $x_1 \leq y_1$ et $x_3 \leq y_3$, alors ($x_1$, $x_2$, $x_3$) $\preccurlyeq$ ($y_1$, $y_2$, $y_3$)

si $x_2 \leq y_2$ et $x_3 \leq y_3$, alors ($x_1$, $x_2$, $x_3$) $\preccurlyeq$ ($y_1$, $y_2$, $y_3$)

si $y_1 \leq x_1$ et $y_2 \leq x_2$, alors ($y_1$, $y_2$, $y_3$) $\preccurlyeq$ ($x_1$, $x_2$, $x_3$) 

si $y_1 \leq x_1$ et $y_3 \leq x_3$, alors ($y_1$, $y_2$, $y_3$) $\preccurlyeq$ ($x_1$, $x_2$, $x_3$) 

si $y_2 \leq x_2$ et $y_3 \leq x_3$, alors ($y_1$, $y_2$, $y_3$) $\preccurlyeq$ ($x_1$, $x_2$, $x_3$).

on a examiné l'ensemble des cas possibles et on en conclut que la relation de préférence notée $\preccurlyeq$ est complète.

1.2
 
Une relationde préférence est dite transitive si quelques soient ($x$, $y$, $z$) $\in {\mathbf{R}}^3$, si $x \preccurlyeq y$ et $y \preccurlyeq z$ alors $x \preccurlyeq z$.

soient $x$ = (2, 4, 4),  $y$ = (1, 4, 5), $z$ = (1, 2, 5).

Ici, $x \preccurlyeq y$ car $x_2 = 4 \leq y_2 = 4$ et $x_3 = 4 \leq y_3 = 5$.
De plus, $y \preccurlyeq z$ car $y_1 = 1 \leq z_1 = 1$ et $y_3 = 5 \leq z_5 = 5$

En revanche, la transitivité n'est pas verifiée car $x_3 = 4 \leq z_3 = 5$, mais $x_1 = 2 \gt z_1 = 1$ et $x_2 = 4 \gt z_2 = 2$.
On ne peut pas dire dans ce cas que $x \preccurlyeq z$.









##Exercice 2B
### 2.1
Discuter du maximum de la fonction d'utilité $U(x,y)=2x^3 + x^2 y - 9x^2 - 2xy + 2x - 4y + 20$ sous les contraintes $x\geq 0$, $y\geq 0$ et la contrainte de revenu $5x+3y\leq r$ pour $r=5$ puis pour $r=20$.
Vérifier avec un dessin du graphe de $U$.

### 2.2
Soit $U:(x,y)\mapsto U(x,y)$ une fonction d'utilité (à valeurs dans $\mathbf{R}$) dont on cherche le maximum sous les contraintes conjointes $c_1(x,y)\leq 0$, $c_2(x,y)\leq 0$ et $c_3(x,y)\leq 0$. On ne précise ni $U$ ni les $c_i$.
On a exécuté avec Sagemath la suite d'instructions ci-dessous et obtenu la réponse qui suit. Que peut on dire des couples $(x,y)$ où $U$ est maximal ? Expliquer.
Que peut on dire des couples $(x,y)$ où $U$ est minimal ?

```python
var('l,m,n')
L = (U-l*c1-m*c2-n*c3).gradient()(x,y)
S = solve([L[0]==0,L[1]==0,l*c1==0,m*c2==0,n*c3==0],[x,y,l,m,n])

print '(x,y), (l,m,n), (c1(x,y),c2(x,y),c3(x,y)) ='
ns = 1
for s in S:
    x,y,l,m,n = (s[i].rhs().n(digits=2) for i in range(5))
    print ns,(x,y),(l,m,n),(c1(x,y),c2(x,y),c3(x,y))
    ns = ns+1

(x,y), (l,m,n), (c1(x,y),c2(x,y),c3(x,y)) =
1 (1.0, -2.0) (0.00, 0.00, 0.00) (-1.0, 2.0, -11.)  
2 (0.00, -1.0) (-2.0, 0.00, 0.00) (0.00, 1.0, -10.)  
3 (0.00, 0.00) (-4.0, -2.0, 0.00) (0.00, 0.00, -5.0)  
4 (1.5, -0.17) (0.00, 0.00, 0.92) (-1.5, 0.17, 0.00)  
5 (0.00, 1.0) (-2.8, 0.00, 0.80) (0.00, -1.0, 0.00)  
6 (1.2, 0.00) (0.00, 0.50, 1.0) (-1.2, 0.00, 0.00)  
```


REPONSES: 

1.1 

Maximiser la fonction $U(x, y)$ se traduit par: 
$ \left\{ \begin{array}{1}
U(x, y) \to max  \\
5x + 3y  \leqslant r \\
x \geqslant  0\ ;\; y\geqslant 0 
\end{array} \right.$

Mais maximiser revient à minimer $- U($x,y$)$:
$ (*) \left\{ \begin{array}{1}
-U(x, y) \to min  \\
5x + 3y - r \leqslant 0 \\
-x \leqslant  0\ ;\; -y\leqslant 0 
\end{array} \right.$

De plus, on met $(*)$ sous la forme: 
$ \left\{ \begin{array}{1}
C(x, y) \to min  \\
g1(x,y)  \leqslant 0 \\
g2(x,y)  \leqslant 0 \\
g3(x,y)  \leqslant 0 \\
 \end{array} \right.$

avec: 
$ \left\{ \begin{array}{1}
C(x, y) = -U(x,y) \\
g1(x,y) = -x \\
g2(x,y) = -y \\
g3(x,y) = 5x + 3y - r \\
 \end{array} \right.$

 Par définition le Lagrangien du problème est:

 $ L(x, y ,\mu_1, \mu_2, \mu_3) = c(x,y) + \mu_1g_1(x, y) +\mu_2g_2(x,y) + \mu_3g_3(x, y)$  
 = $(-2x^3 - x^2y + 9x^2 + 2xy - 2x + 4y - 20) -\mu_1x -\mu_2y + \mu_3(5x + 3y - r) $ \\

Les conditions de KKT disent qu'en $\bar x$, solution de $(*)$, ∃ $(\mu_1, \mu_2, \mu_3)$  $ {\displaystyle \in }$ $\mathbb R^3$ tel que: 
 0 = $\nabla x L((\bar x,\bar y),\bar \mu)$ = $-\nabla u(x,y) + \mu_1(-1,0) + \mu_2(0, -1) + \mu_3(5,3)$

avec $\mu_1 \geqslant  0, \mu_2 \geqslant  0, \mu_3 \geqslant  0$ et 

$\mu_1 - \bar x = 0$

$ \mu_2 - \bar y = 0$

$ \mu_3(5 \bar x + 3\bar y - r) = 0 $ 

la relation (*) se récrit: ∃ $(\mu_1, \mu_2; \mu_3) \geqslant 0$ tels que: $\nabla (\bar x, \bar y) = \mu_3(5,3) + (-\mu_1, -\mu_2)$ 

Voici les différents cas possibles: 

**cas numéro 1**: si la solution $(\bar x, \bar y)$ est à l'intérieur des contraintes et si l'on a $\bar x \geqslant  0, \bar y \geqslant  0$  et $ 5 \bar x + 3\bar y \leqslant  r $, par complémentarité $\bar \mu_1 = \bar \mu_2 = \bar \mu_3 = 0$ et  $\nabla (\bar x, \bar y) = 0 $

Donc $ \frac{∂U}{∂x} (x,y) = 6x^2 + 2xy - 18x - 2y + 2$
 et $\frac{∂U}{∂y}(x,y) = x^2 - 2x - 4$ 

Pour $ x^2 - 2x - 4 = 0$, $ \triangle = 20$, on a deux solutions:

$ x_1 = -\sqrt 5 + 1 $ => pas de solution car la condition est que  $x \geqslant  0$

$ x_2 = \sqrt 5 + 1 $ =>
Lorsque l'on remplace $x_2$ dans  la fonction $u(x,y): y = -19$, ainsi cela ne respecte pas la condition $y \geqslant  0$. Nous pouvons exclure le cas numéro 1. 

**cas numéro 2**: $(\bar x, \bar y) = (0,0)$ , alors $u(\bar x, \bar y) = 20 $.  
Ainsi on voit que les contraintes de KKT impliquent que la contrainte de budget doit être active, les solutions en coins n'étant pas exclus ( cas où $ \bar x $ ou $\bar y = 0 $)

**cas numéro 3**: $\bar x = 0$. On a donc $\bar y = \frac{r}{P_2}$ donc $ \frac 53 $ pour r = 5 et $\frac{20}{3} $  pour r = 20 

**cas numéro 4**: $\bar y $ = 0. On a donc $\bar x$ = $\frac{r}{P_1}$ donc $ 1 pour r = 5 et 4 pour r = 20 

Pour r = 5: 
   
   cas numéro 3: $u(0; \frac 53) = \frac{40}{3} $ \\
   cas numéro 4: $ u(1;0) = 15 $

Ainsi pour r = 5 on peut supprimer les cas numéros 3 et 4.

Pour r = 20 : 

cas numéro 3: $u(0; \frac{20}{3}) = -\frac{20}{3}$ \\
cas numéro 4: $u(4,0) = 20 $\\
Donc pour r = 20, on peut supprimer le cas numéro 3.

**cas numéro 5**: cas où l'on est sur la contrainte mais pas sur l'un des coins. \\
Il faut maximiser l'utilité sur le segment qui relie $(0; \frac r3)$ à $(0, \frac r5)$ \\
$ y = \frac 13 (r - 5x) $ \\
On a donc à maximiser la fonction: \\
$ C(x) = u(x, \frac 13(r - 5x)) $ \\

$C(x) = \frac 13 x^2 $ + $(\frac 13 r - \frac{17}{3})x^2$ + $(-\frac 23r + \frac{26}{3})x $ + $(-\frac 43 r + 20)$ \\
On a alors: \\
$ C'(x) = x^2 $ + $(\frac 23 r - \frac{34}{3})x $ - $\frac 23 r + \frac{26}{3} $  \\

Pour $r = 5$ :\\
$ C'(x) = x^2 - 8x + \frac{16}{3} $ \\
$ \triangle = \frac{128}{3}$ \\
$ \bar x = \frac{-4\sqrt 6 + 12}{3} $ \\
$ \bar y = \frac 13(5 - \bar x) = \frac{20\sqrt6 - 45}{9}$ 

Donc  $\bar x$ et $\bar y$ qui maximisent l'utilité pour $r = 5$ sont $\bar x = \frac{-4\sqrt 6 + 12}{3}$ et $\bar y = \frac{20\sqrt6 - 45}{9}$ \\

Pour $r = 20$ : \\
 $ C'(x) = x^2 + 2x - \frac{14}{3}$ \\
 $\triangle = \frac{68}{3}$

$ x_1 = \frac{-\sqrt 51 + 3}{3} \leqslant 0 $ donc ce n'est pas une solution 

$ x_2 = \frac{\sqrt51 + 3}{3}$ \\
$ y = \frac 13( 5 - 5\bar x)$ = $ - \frac{5\sqrt 51}{9}$

Donc  $\bar x$ et $\bar y$ qui maximisent l'utilité pour $r = 20$ sont $\bar x = \frac{\sqrt51 + 3}{3}$ et $\bar y = - \frac{5\sqrt 51}{9}$


















## Exercice 3C
On considère le jeu de poker simplifié à deux joueurs suivant. Trois mains sont possibles, numérotées de $1$ à $3$, de la plus faible à la plus forte. Chaque joueuse, ayant reçu l'une de ces mains, met un jeton au pot. Le jeu se déroule ensuite selon le schéma ci-dessous (jeu séquentiel), sachant que, pour _miser_ ou pour _voir_, une joueuse doit rajouter un jeton au pot (rien à mettre au pot si la joueuse choisit de _passer_). La gagnante remporte le pot. 
La joueuse 1 triche et, à l'insu de la joueuse 2, s'est arrangée avec le croupier qui distribue les cartes afin que la main $(3, 2)$ (qui lui est favorable) sorte plus souvent que les autres, avec une probabilité de $1/4$ (les cinq autres mains sortant avec une même probabilité de $3/20$).

![Règles du jeu](https://github.com/jbcaillau/ande/blob/master/proj/poker.png?raw=1)

### 3.1
Calculer la matrice des gains (en espérance) du jeu sous forme normale.

### 3.2
Déterminer les stratégies _prudentes_ de chaque joueuse, c'est à dire la stratégie $\max_i \min_j$ pour la joueuse 1 et $\min_j \max_i$ de la joueuse 2. Y a-t-il équilibre (en stratégies pures) ?

### 3.3
Déterminer les éventuelles stratégies dominées de chaque joueuse.

### 3.4
Déterminer la valeur du jeu en stratégies mixtes, et donner un couple de stratégies mixtes en équilibre.

### 3.5
Un nouveau croupier remplace le précédent. Quatre mains sont désormais possibles, numérotées de $1$ à $4$, de la plus faible à la plus forte. Donner l'ensemble des stratégies (pures) pour chaque joueuse dans le jeu sous forme normale.

### 3.6 (BONUS)
Reprendre les questions 3.1 à 3.5 en supposant le nouveau croupier honnête, de sorte que toutes les combinaisons de mains sont équiprobables.

REPONSES :

3.1
On note mise M, voit V, passe P, $J_1$ la joueuse 1 et $J_2$ la joueuse 2.

La joueuse 1 commence à jouer.
Pour réaliser sa stratégie $S_1$, $J_1$ a 3 choix : (M, PV, PP) 
(par exemple, PV signifie: Passe puis Voit si $J_2$ Mise)

Donc, $S_1$ = $\{$M, PV, PP$\}$ $*$ $\{$M, PV, PP$\}$ $*$ $\{$M, PV, PP$\}$ ( *{ensemble des stratégies si main = 1} $*$ {ensemble des stratégies si main=2} $*$ {ensemble des stratégies si main = 3}*) 

Joue ensuite la joueuse 2. Si $J_1$ joue M, $J_2$ a 2 choix : (V, P). Si $J_1$ joue P, $J_2$ a deux choix également: (M, P). On a $\{$V, P$\}$ $*$ $\{M, P \} = \{VP, VM, PP, PM\}$ (par exemple, VP signifie: Voit si la joueuse 1 Mise et Passe si la joueuse 1 Passe).

Au final, comme $J_2$ doit choisir sa stratégie pour chacune de trois mains: $S_2 = \{VP, VM, PP, PM\} * \{VP, VM, PP, PM\} *\{VP, VM, PP, PM\}$

$Card ( S_1) = 3^3 = 27$ et $Card(S_2) = 4^3=64$

Ainsi le tables des gains en espérance est de taille $27 * 64= 1728$ cases.


---


Calcul des gains en espérance:

 soit $M_1$ = (main de $J_1$,main de $J_2$) $\in$ {$(1,2), (1,3), (2,1), (2,3), (3,1), (3,2)$} = $\omega$

 La valeur du gain de $J_1$ est connue: $g_1(s_1,s_2) = \mathbb E(g_1(s_1,s_2,M_1)$

 c'est-à-dire: $g_1(s_1,s_2) = \sum g_1(s_1,s_2,m) * P(M_1 = m)$ avec $m \in \omega$
>  Dans notre cas, $ P(M_1 = (3,2)) = \frac{1}{4}$ et $ P(M_1 = a) = \frac{3}{20}$ avec $a \in \omega \setminus {(3,2)}$

Supposons $s_1 = (PV,PP,M)$ et $s_2 = (VM,PM,VM)$


1.   si $M_1$=$(1,2)$, la séquence du jeu est P $\to$ M $\to$ V. Ainsi le pot contient 4 jetons et la joueuse 1 perd sa mise et $g_1(s_1,s_2,(1,2))= -2$
2.    si $M_1$=$(1,3)$, la séquence du jeu est P $\to$ M $\to$ V. Ainsi le pot contient 4 jetons et la joueuse 1 perd sa mise et $g_1(s_1,s_2,(1,3))= -2$
3.    si $M_1$=$(2,1)$, la séquence du jeu est P $\to$ M $\to$ P. Ainsi le pot contient 3 jetons et la joueuse 1 perd sa mise et $g_1(s_1,s_2,(1,2))= -1$
4.  si $M_1$=$(2,3)$, la séquence du jeu est P $\to$ M $\to$ P . Ainsi le pot contient 3 jetons et la joueuse 1 perd sa mise et $g_1(s_1,s_2,(1,2))= -1$
5.  si $M_1$=$(3,1)$, la séquence du jeu est M $\to$ V. Ainsi le pot contient 4 jetons et la joueuse 1 perd sa mise mais remporte le pot et $g_1(s_1,s_2,(1,2))= -2+4 = 2$
6.  si $M_1$=$(3,2)$, la séquence du jeu est M $\to$ P. Ainsi le pot contient 3 jetons et la joueuse 1 perd sa mise mais remporte le pot et $g_1(s_1,s_2,(1,2))= -2 +3 = 1$

Avec la fonction $\mathtt g\mathtt m\mathtt f\mathtt u\mathtt n (s_1,s_2,main)$ on calcule les gains de la joueuse 1 selon les stratégies $s_1$ et $s_2$ pour chaque couple de main $M_1$

Avec ces résultats, on peut calculer les gains en espérance de $J_1$ pour $s_1$ et $s_2$ définies. Ici:


$g_1(s_1,s_2) = (-2-2-1-1+2) * \frac {3}{20} + 1 * \frac {1}{4} =  \frac {-12}{20}  + \frac{1}{4} = \frac{-7}{20} \lt 0$

Avec la fonction $\mathtt g\mathtt f\mathtt u\mathtt n (s_1,s_2)$ on calcule le gain en espérance de $J_1$ selon les stratégies $s_1$ et $s_2$ données. 

Comme le jeu est à somme nulle, $g_1(s_1,s_2) = -g_2(s_1,s_2)$. Donc $g_2(s_1,s_2) = \frac {7}{20}$

Ainsi $g(s_1,s_2) = (\frac{-7}{20},\frac{7}{20})$ ;
ce couple correspond à une seule case du tableau des gains du jeu sous forme normale. La matrice des gains est la matrice $A_{m,n}$ telle que: \\
 $g_1(s_1,s_2) = -g_2(s_1,s_2) = a_{i,j}$ , avec $i =\{ 1,..,m\}$ et $j =\{ 1,..,n\}$
 La matrice A des gains en espérance est donnée par : 


```
A = np.zeros((m, n))
for i in range(0, m):
    for j in range(0, n):
        A[i, j] = gfun(S1[i], S2[j])
```





3.2

On cherche les stratégies _prudentes_, la stratégie  $max_imin_j$  pour la joueuse 1 et  $min_jmax_i$  de la joueuse 2.

Pour la joueuse 1, on créé une fonction maxmin( ) qui va maximiser le pire gain. C'est à dire que parmi les plus petites valeurs de chaque colonne, elle va trouver la plus élevée. \\
Pour la joueuse 2, on créé une fonction minmax( ) qui va minimiser la pire perte. C'est a dire que parmi les plus grandes valeurs de chaque ligne, elle va trouver la plus basse. \\
On obtien les codes suivants : 

```
def maxmin(m,n):
    e=0
    b =[]
    I =[]
    J =[]
    for j in range (0,n):
      a = np.max(A)
      for i in range (0,m):
           if A[i,j] < a : a = A[i,j]
      b.append(a)
      I.append(i)
      J.append(j)
    e= b.count(max(b))
    return(e,max(b), I[b.index(max(b))], J[b.index(max(b))])

def minmax(m,n):
    e=0
    b =[]
    I =[]
    J =[]
    for i in range (0,m):
      a = np.min(A)
      for j in range (0,n):
           if A[i,j] > a : a = A[i,j]
      b.append(a)
      I.append(i)
      J.append(j)
    e= b.count(min(b))
    return(e,min(b), I[b.index(min(b))], J[b.index(min(b))])

```
A l'aide de ces deux fonctions, on obtient $\alpha = 2.4$ et $\beta = 2.4$
Lorsque $\alpha = \beta$, on a un equilibre. 










In [100]:
import numpy as np
from scipy.optimize import linprog

# Exceptions
class StrategieInconnue(Exception):
    """Strategie Inconnue
    
    Attribut :
        s -- stratégie
    """
    def __init__(self, s):
        self.s = s

class MainInconnue(Exception):
    """Main Inconnue
    
    Attribut :
        m -- main
    """
    def __init__(self, m):
        self.m = m

class MainVide(Exception):
    """Main Vide
    """

class PbResolution(Exception):
    """Probleme de resolution du LP
    """

# Stratégies de la joueuse 1
S1m = [ 'M', 'PV', 'PP' ] # M = Mise, P = Passe, V = Voit
l1 = len(S1m)
S1 = [ (S1m[i], S1m[j], S1m[k]) for i in range(0, l1) for j in range(0, l1) for k in range(0, l1) ]
m = len(S1)

# Stratégies de la joueuse 2
S2m = [ 'VP', 'VM', 'PP', 'PM' ] # M = Mise, P = Passe, V = Voit
l2 = len(S2m)
S2 = [ (S2m[i], S2m[j], S2m[k]) for i in range(0, l2) for j in range(0, l2) for k in range(0, l2) ]
n = len(S2)

# Mains pouvant être distribuées
Mains = [ (1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2) ] # main 1 < main 2 < main 3

# Calcul des gains
def gmfun(s1, s2, main):
    """g = gmfun(s1, s2, main)
    Gain de la joueuse 1 en fonction de la main distribuée aux deux joueuses.

    s1 : triplet de stratégies de la joueuse 1
    s2 : triplet de stratégies de la joueuse 2
    main : main (= cartes) distribuées aux joueuses
    """
    if s1 not in S1: raise StrategieInconnue(s1)
    if s2 not in S2: raise StrategieInconnue(s2)
    if main not in Mains: raise MainInconnue(main)

    s1m = s1[main[0]-1]
    s2m = s2[main[1]-1]

    if s1m[0] is 'M': # la joueuse 1 mise

        if s2m[0] is 'V': # la joueuse 2 voit
            if main[0] > main[1]: gm = 2 # la meilleure main emporte le pot
            else: gm = -2
        elif s2m[0] is 'P': # la joueuse 2 passe
            gm = 1 # la joueuse 1 emporte le pot
        else: raise StrategieInconnue(s2)

    elif s1m[0] is 'P': # la joueuse 1 passe

        if s2m[1] is 'P': # la joueuse 2 passe
            if main[0] > main[1]: gm = 1 # la meilleure main emporte le pot
            else: gm = -1
        elif s2m[1] is 'M': # la joueuse 2 mise
            if s1m[1] is 'V': # la joueuse 1 voit
                if main[0] > main[1]: gm = 2 # la meilleure main emporte le pot
                else: gm = -2
            elif s1m[1] is 'P': # la joueuse 1 passe
                gm = -1
            else: raise StrategieInconnue(s1)
        else: raise StrategieInconnue(s2)

    else: raise StrategieInconnue(s1)

    return gm

def gfun(s1, s2):
    """g = gfun(s1, s2)
    Gain en espérance de la joueuse 1 (toutes les mains sont supposées équiprobables)
 
    s1 : triplet de stratégies de la joueuse 1
    s2 : triplet de stratégies de la joueuse 2
    """
    l = len(Mains)
    if l is 0: raise MainVide
    """ANCIEN CODE
    """
    """g = 0.
    for i in range(0, l):
        g = g + (1/l) * gmfun(s1, s2, Mains[i])
    return g
    """
    g = 0.
    for i in range(0, l):
      if Mains[i] == (3,2): g = g + (1/4) * gmfun(s1, s2, Mains[i])
      else: g = g + (3/20) * gmfun(s1, s2, Mains[i])
    return g


A = np.zeros((m, n))
for i in range(0, m):
    for j in range(0, n):
        A[i, j] = gfun(S1[i], S2[j])

d = abs(np.min(A)) + 1
A = A + d
print(A) # translate les gains pour garantir une valeur > 0 du jeu mixte

def maxmin(m,n):
    e=0
    b =[]
    I =[]
    J =[]
    for j in range (0,n):
      a=np.max(A)
      for i in range (0,m):
           if A[i,j] < a : a = A[i,j]
      b.append(a)
      I.append(i)
      J.append(j)
    e= b.count(max(b))
    return(e,max(b), I[b.index(max(b))], J[b.index(max(b))])

p1= maxmin(m,n)
print(p1)

def minmax(m,n):
    e=0
    b =[]
    I =[]
    J =[]
    for i in range (0,m):
      a = np.min(A)
      for j in range (0,n):
           if A[i,j] > a : a = A[i,j]
      b.append(a)
      I.append(i)
      J.append(j)
    e= b.count(min(b))
    return(e,min(b), I[b.index(min(b))], J[b.index(min(b))])

p2=minmax(m,n)
print(p2)

# Calcul de la valeur du jeu en stratégies mixtes (minimax)
c =-np.ones(n) # min (c|x) = -max (-c|x)
b = np.ones(m) # Ax <= b 
bounds = (0, None) # 0 <= x

method='simplex'
#method='revised simplex'
#method='interior-point'

res = linprog(c, A_ub=A, b_ub=b, bounds=bounds, method=method)
if not res.success: raise PbResolution

v = 1 / (-res.fun)
x = v * res.x
v = v - d
xx = np.round_(x, decimals=8)

print('v = ', v)
print('x = ', xx)
print('')
print("Stratégie mixte optimale de la joueuse 2 :")
for j in range(0, n):
    if xx[j] > 0:
        print(S2[j], "avec proba", xx[j])

[[2.5 2.5 3.4 ... 2.4 3.3 3.3]
 [2.1 2.1 3.  ... 2.8 3.7 3.7]
 [2.1 2.1 3.  ... 1.6 2.5 2.5]
 ...
 [2.8 2.8 2.8 ... 2.1 2.1 2.1]
 [2.4 2.4 2.4 ... 2.5 2.5 2.5]
 [2.4 2.4 2.4 ... 1.3 1.3 1.3]]
(5, 2.4, 26, 2)
(4, 2.4, 14, 63)
v =  0.08333333333333304
x =  [0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.33333333 0.         0.
 0.         0.         0.         0.         0.         0.2
 0.         0.         0.         0.13333333 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.33333333 0.         0.
 0.         0.         0.         0.        ]

Stratégie mixte optimale de la joueuse 2 :
('PP', 'VP', 'VM') avec proba 0.33333333
('PP', 'PP', 'VM') avec